[package]
name = "prej"
version = "0.8.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
anyhow = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
clap = {version = "4.6.1", features = ["cargo"]}
ignore = "0.4.25"
yaml_serde = "0.10"
